In [1]:
import torch

In [4]:
matrix = torch.randint(10,40,(2,3))
matrix

tensor([[37, 28, 33],
        [28, 19, 24]])

In [ ]:
# Toplama
# Çıkarma
# Çarpma
# Bölme
# Üs alma
# Cebirsel çarpım

### Toplama

In [ ]:
scalar_sum = matrix + 10
scalar_sum

tensor([[38, 32, 26],
        [46, 22, 25]])

### Çıkarma

In [ ]:
scalar_sub = matrix - 10
scalar_sub

tensor([[18, 12,  6],
        [26,  2,  5]])

### Çarpma

In [5]:
scalar_mul = matrix * 10
scalar_mul

tensor([[280, 220, 160],
        [360, 120, 150]])

### Bölme

In [6]:
scalar_div = matrix / 2
scalar_div

tensor([[14.0000, 11.0000,  8.0000],
        [18.0000,  6.0000,  7.5000]])

### Üs Alma

In [7]:
scalar_exp = matrix ** 2
scalar_exp

tensor([[ 784,  484,  256],
        [1296,  144,  225]])

## Tensorler Arası İşlemler

In [5]:
matrix2 = torch.randint(1,10,(2,3))
matrix2, matrix

(tensor([[1, 6, 7],
         [9, 3, 4]]),
 tensor([[37, 28, 33],
         [28, 19, 24]]))

### Tensor Toplama

In [ ]:
tensor_sum = matrix2 + matrix
#tensor_sum = torch.add(matrix, matrix2)
tensor_sum

tensor([[31, 31, 22],
        [37, 20, 24]])

### Tensor Çıkarma

In [14]:
tensor_sub = matrix - matrix2
#tensor_sub = torch.sub(matrix, matrix2)
tensor_sub

tensor([[25, 13, 10],
        [35,  4,  6]])

### Tensor Çarpma

In [ ]:
tensor_mul = matrix * matrix2
#tensor_mul = torch.mul(matrix, matrix2)
tensor_mul

### Cebirsel Çarpma

In [ ]:
algebric_mul = torch.matmul(matrix, matrix2.T) #matrix2.T matrixin devriğini alır çünkü cebirsel çarpma için gereklidir
#algebric_mul = matrix @ matrix2.T
algebric_mul    

tensor([[436, 549],
        [310, 405]])

In [ ]:
tensor_div = matrix / matrix2
#tensor_div = torch.div(matrix, matrix2)
tensor_div

tensor([[37.0000,  4.6667,  4.7143],
        [ 3.1111,  6.3333,  6.0000]])